---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart dockbeat
  become: yes
  service:
    name: dockbeat
    state: restarted

- name: restart packetbeat
  become: yes
  service:
    name: packetbeat
    state: restarted